"""Add update_strava_desc user setting

Revision ID: 23c757641f3f
Revises: b00b80ec0f51
Create Date: 2025-04-06 17:36:10.464940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23c757641f3f"
down_revision: Union[str, None] = "b00b80ec0f51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("update_strava_desc", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "update_strava_desc")
    # ### end Alembic commands ###
