"""Add last_backlog_sync column to user

Revision ID: 5ee33b93abdb
Revises: f99ba4e43068
Create Date: 2025-02-22 19:42:31.493108

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import rg_app.db.decorators

# revision identifiers, used by Alembic.
revision: str = "5ee33b93abdb"
down_revision: Union[str, None] = "f99ba4e43068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_backlog_sync", rg_app.db.decorators.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_backlog_sync")
    # ### end Alembic commands ###
