"""add last login and signup dates

Revision ID: 65d82432538d
Revises: b0f19f3f6010
Create Date: 2024-09-12 21:07:56.318202

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65d82432538d"
down_revision: Union[str, None] = "b0f19f3f6010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column("user", sa.Column("last_login", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
