"""Change update_desc column type to int

Revision ID: a11b2b488b7e
Revises: 806238fe62ae
Create Date: 2025-04-20 18:55:39.285626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a11b2b488b7e"
down_revision: Union[str, None] = "806238fe62ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "update_strava_desc")
    op.add_column("user", sa.Column("update_strava_desc", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "update_strava_desc")
    op.add_column(
        "user", sa.Column("update_strava_desc", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###
