"""Add regions

Revision ID: f99ba4e43068
Revises: ff4d8a2b7620
Create Date: 2024-11-28 21:33:24.741668

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f99ba4e43068"
down_revision: Union[str, None] = "ff4d8a2b7620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "region",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("ancestors", postgresql.ARRAY(sa.String(length=16), dimensions=1), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_region_type"), "region", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_region_type"), table_name="region")
    op.drop_table("region")
    # ### end Alembic commands ###
