"""Add activities

Revision ID: ff4d8a2b7620
Revises: 65d82432538d
Create Date: 2024-11-24 22:15:41.794354

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff4d8a2b7620"
down_revision: Union[str, None] = "65d82432538d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("moving_time", sa.BigInteger(), nullable=False),
        sa.Column("elapsed_time", sa.BigInteger(), nullable=False),
        sa.Column("distance", sa.Numeric(precision=8, scale=1), nullable=False),
        sa.Column("track", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("track_is_detailed", sa.Boolean(), nullable=False),
        sa.Column("elevation_gain", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("elevation_low", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("elevation_high", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("sport_type", sa.String(length=32), nullable=False),
        sa.Column("gear_id", sa.String(length=32), nullable=True),
        sa.Column("visited_regions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("visited_regions_additional", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    # ### end Alembic commands ###
